### ISSUE TITLE
try-catch

### ISSUE THREAD

**Issue by RicardoMellen** [ralamarti/Software-Quality-Project#6]
You must have a try-catch in the main class.

**Comment by ralamarti** [comment]
I created a new Branch (IssuesSolved) where we will solve the problems. I added the try-catch structure.

**Comment by ralamarti** [comment]
Also added try-catch at the InboxScreen class, on the method that handles continuing to the NewMailScreen window.

**Comment by ralamarti** [comment]
And also at the NewMailScreen class, on the method that handles going back to the InboxScreen

**Comment by ralamarti** [comment]
And on ConfigScreen to the methods that control the buttons.
